name: dart_test_analyze_format
on: [push, pull_request]
jobs:
  dart_test_analyze_format:
    runs-on: ubuntu-latest
    container: google/dart
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install make
      - run: git clone https://github.com/linux-test-project/lcov.git
      - run: make -C lcov install
      - run: dart pub get
      - run: dart test --coverage .
      - run: dart pub run coverage:format_coverage -i . -l > coverage.lcov
      - run: lcov -l coverage.lcov
      - run: dart analyze
      - run: dart format --set-exit-if-changed .
